version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    networks:
      - es-net
    ports:
      - 9200:9200
    restart: unless-stopped
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    restart: unless-stopped
networks:
  es-net:
    driver: bridge
